# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-26 07:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntryPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('url', models.CharField(max_length=255, verbose_name='入口页面')),
                ('url_pattern', models.CharField(max_length=255, verbose_name='抓取网页的URL正则表达式')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('default_freq', models.IntegerField(help_text='单位秒', verbose_name='默认的频率')),
                ('title_selector', models.CharField(max_length=255, null=True, verbose_name='标题选择器')),
                ('body_selector', models.CharField(max_length=255, null=True, verbose_name='正文选择器')),
                ('status', models.IntegerField(default=0, help_text='0为正常', verbose_name='状态')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_md5', models.CharField(max_length=32, unique=True, verbose_name='网页ID')),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
                ('content', models.TextField(blank=True, null=True, verbose_name='网页内容')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='文章标题')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='抓取时间')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spider_app.EntryPoint')),
            ],
        ),
    ]
