# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-27 02:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spider_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='项目名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
            ],
            options={
                'verbose_name_plural': '生活圈列表',
                'verbose_name': '生活圈',
            },
        ),
        migrations.AlterModelOptions(
            name='entrypoint',
            options={'verbose_name': '入口页', 'verbose_name_plural': ' 入口页列表'},
        ),
        migrations.AlterField(
            model_name='entrypoint',
            name='body_selector',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='正文选择器'),
        ),
        migrations.AlterField(
            model_name='entrypoint',
            name='title_selector',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='标题选择器'),
        ),
        migrations.AddField(
            model_name='entrypoint',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spider_app.Project', verbose_name='项目'),
        ),
    ]
