# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider_app', '0002_auto_20170727_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrypoint',
            name='last_exec_time',
            field=models.DateTimeField(null=True, verbose_name='最后执行时间'),
        ),
    ]
